<<<<<<< HEAD
# Generated by Django 3.1 on 2021-02-09 20:53
=======
# Generated by Django 3.1 on 2024-12-26 17:55
>>>>>>> a1a51b03e61ddd11f3321dc643d2ca2a3ab46f5b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
