# Generated by Django 3.1 on 2025-01-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201006_0125'),
        ('category', '0002_auto_20241216_1639'),
    ]

    operations = [
    ]
